export const CLAIMABLE_FETCH_BALANCES_BEGIN = 'CLAIMABLE_FETCH_BALANCES_BEGIN';
export const CLAIMABLE_FETCH_BALANCES_SUCCESS = 'CLAIMABLE_FETCH_BALANCES_SUCCESS';
export const CLAIMABLE_FETCH_BALANCES_FAILURE = 'CLAIMABLE_FETCH_BALANCES_FAILURE';

export const CLAIMABLE_FETCH_APPROVAL_BEGIN = 'CLAIMABLE_FETCH_APPROVAL_BEGIN';
export const CLAIMABLE_FETCH_APPROVAL_SUCCESS = 'CLAIMABLE_FETCH_APPROVAL_SUCCESS';
export const CLAIMABLE_FETCH_APPROVAL_FAILURE = 'CLAIMABLE_FETCH_APPROVAL_FAILURE';
